# Generated by Django 4.2.3 on 2023-07-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.TextField()),
                ('registry_code', models.TextField()),
                ('key', models.TextField()),
            ],
        ),
    ]
